name: SEO Rank Tracker

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "requirements.txt not found!"

      - name: Debug file structure
        run: ls -R  # 列出所有文件，检查 `requirements.txt` 是否存在

      - name: Run SEO Rank Tracker
        run: python seo-rank-tracker.py
